# Generated by Django 4.1.4 on 2023-12-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='person',
            new_name='user',
        ),
    ]
