# Generated by Django 4.1.4 on 2023-12-18 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_imagepoem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepoem',
            name='author',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='image_poem', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
